services:
  shop-app: 
    container_name: shop-app 
    build:
      context: .
      dockerfile: ./Dockerfile 
      target: runtime
    ports:
      - "5179:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:80      
      CONNECTIONSTRINGS__SHOPAPP: "Host=shop-postgres;Port=5432;Database=shopapp;Username=postgres;Password=postgres;Include Error Detail=true"
    depends_on:
      - shop-postgres
  shop-postgres: 
    container_name: shop-postgres 
    image: postgres:16         
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shopapp"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres